// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type coachTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *coachTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("coach").
func (v *coachTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *coachTableType) Columns() []string {
	return []string{
		"id",
		"name",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *coachTableType) NewStruct() reform.Struct {
	return new(Coach)
}

// NewRecord makes a new record for that table.
func (v *coachTableType) NewRecord() reform.Record {
	return new(Coach)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *coachTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// CoachTable represents coach view or table in SQL database.
var CoachTable = &coachTableType{
	s: parse.StructInfo{
		Type:    "Coach",
		SQLName: "coach",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Coach).Values(),
}

// String returns a string representation of this struct or record.
func (s Coach) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[3] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Coach) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Coach) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Coach) View() reform.View {
	return CoachTable
}

// Table returns Table object for that record.
func (s *Coach) Table() reform.Table {
	return CoachTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Coach) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Coach) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Coach) HasPK() bool {
	return s.ID != CoachTable.z[CoachTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Coach) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = CoachTable
	_ reform.Struct = (*Coach)(nil)
	_ reform.Table  = CoachTable
	_ reform.Record = (*Coach)(nil)
	_ fmt.Stringer  = (*Coach)(nil)
)

func init() {
	parse.AssertUpToDate(&CoachTable.s, new(Coach))
}
