// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type placeTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *placeTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("place").
func (v *placeTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *placeTableType) Columns() []string {
	return []string{
		"id",
		"name",
		"address",
		"description",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *placeTableType) NewStruct() reform.Struct {
	return new(Place)
}

// NewRecord makes a new record for that table.
func (v *placeTableType) NewRecord() reform.Record {
	return new(Place)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *placeTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// PlaceTable represents place view or table in SQL database.
var PlaceTable = &placeTableType{
	s: parse.StructInfo{
		Type:    "Place",
		SQLName: "place",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "Address", Type: "string", Column: "address"},
			{Name: "Description", Type: "string", Column: "description"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Place).Values(),
}

// String returns a string representation of this struct or record.
func (s Place) String() string {
	res := make([]string, 6)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "Address: " + reform.Inspect(s.Address, true)
	res[3] = "Description: " + reform.Inspect(s.Description, true)
	res[4] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[5] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Place) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.Address,
		s.Description,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Place) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.Address,
		&s.Description,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Place) View() reform.View {
	return PlaceTable
}

// Table returns Table object for that record.
func (s *Place) Table() reform.Table {
	return PlaceTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Place) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Place) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Place) HasPK() bool {
	return s.ID != PlaceTable.z[PlaceTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Place) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = PlaceTable
	_ reform.Struct = (*Place)(nil)
	_ reform.Table  = PlaceTable
	_ reform.Record = (*Place)(nil)
	_ fmt.Stringer  = (*Place)(nil)
)

func init() {
	parse.AssertUpToDate(&PlaceTable.s, new(Place))
}
